name: 'Grafana E2E versions'
description: 'Resolve Grafana versions for use in E2E tests'
author: 'plugins-platform@grafana'

inputs:
  version-resolver-type:
    required: true 
    type: choice
    default: plugin-grafana-dependency
    description: >
     Choose between different version resolver types.
      plugin-grafana-dependency: Resolve versions based on the Grafana version specified in the plugin.json file.
      minimum-support-obligation: Resolve versions according to Grafana's plugin compatibility policy. I.e. the latest major version and the last minor of the previous major version.
    options: 
      - plugin-grafana-dependency
      - minimum-support-obligation

output:
  matrix:
    description: 'Versions to test against'

runs:
  using: node20
  main: ./output/index.js
